services:

  smia:
    image: ekhurtado/smia:latest-alpine
    container_name: smia
    environment:
      - AAS_MODEL_NAME=SMIA_tutorial_1.aasx
      - AAS_ID=https://example.com/ids/sm/5025_6142_2052_1473
      - AGENT_ID=admin@ejabberd
      - AGENT_PASSWD=asd
    depends_on:
      xmpp-server:
        condition: service_healthy
    volumes:
      - ./aas:/smia_archive/config/aas

  xmpp-server:
    image: ghcr.io/processone/ejabberd
    container_name: ejabberd
    environment:
      - ERLANG_NODE_ARG=admin@ejabberd
      - ERLANG_COOKIE=dummycookie123
      #- CTL_ON_CREATE=! register admin localhost asd
      - CTL_ON_CREATE=! register admin ejabberd asd && register operator001 ejabberd gcis1234
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
    volumes:
      - ./xmpp_server/ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
    healthcheck:
      test: netstat -nl | grep -q 5222
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  smia-operator:
    image: ekhurtado/smia-use-cases:latest-operator
    container_name: smia-operator
    environment:
      - AAS_MODEL_NAME=SMIA_Operator_article.aasx
      - AGENT_ID=operator001@ejabberd
      - AGENT_PSSWD=gcis1234
    depends_on:
      xmpp-server:
        condition: service_healthy
    volumes:
      - ./aas:/smia_archive/config/aas
    ports:
      - 10000:10000